ALTER TABLE ADMON.USUARIO RENAME TO USUARIO_BK;
CREATE TABLE ADMON.USUARIO 
   (USUARIO_ID NUMBER(*,0)  NOT NULL , 
	NOMBRE VARCHAR2(200 CHAR)  NOT NULL , 
	CORREO VARCHAR2(300 CHAR), 
	CORREO_ALTERNO VARCHAR2(300 CHAR), 
	PUESTO_ID NUMBER(*,0), 
	PREGUNTA_ID NUMBER(*,0), 
	RESPUESTA VARCHAR2(300 CHAR), 
	DESCRIPCION VARCHAR2(999 CHAR), 
	USUARIO VARCHAR2(100 CHAR), 
	CONTRASENA VARCHAR2(100 CHAR), 
	ZONA_ID NUMBER(*,0), 
	APELLIDO_PATERNO VARCHAR2(200 CHAR), 
	APELLIDO_MATERNO VARCHAR2(200 CHAR), 
	TELEFONO VARCHAR2(200 CHAR), 
	EXTENCION VARCHAR2(200 CHAR), 
	CELULAR VARCHAR2(200 CHAR), 
	CREACION_FECHA DATE DEFAULT SYSDATE NOT NULL , 
	CREACION_USUARIO NUMBER(*,0)  NOT NULL , 
	MODIFICACION_FECHA DATE, 
	MODIFICACION_USUARIO NUMBER(*,0), 
	ESTATUS_ID NUMBER(*,0)  NOT NULL , 
	ELIMINADO_ID NUMBER(*,0) DEFAULT 0  NOT NULL , 
	IGNORA_MAC NUMBER DEFAULT 0  NOT NULL, 
	CODIGO_CONTROL_ACCESOS NUMBER, 
	CONTRASENA_WEBLOGIC VARCHAR2(100 CHAR), 
	FECHA_ULTIMA_SESION DATE, 
	FECHA_VIGENCIA DATE, 
	CONSTRAINT PK_USUARIOS PRIMARY KEY (USUARIO_ID)
   )
   COMMENT ON COLUMN ADMON.USUARIO.USUARIO_ID IS 'Numero identificador de Usuarios';
 
   COMMENT ON COLUMN ADMON.USUARIO.NOMBRE IS 'Nombre de usuario';
 
   COMMENT ON COLUMN ADMON.USUARIO.CONTRASENA IS 'Contraseña';
 
   COMMENT ON COLUMN ADMON.USUARIO.NOMBRE IS 'Nombre real';
 
   COMMENT ON COLUMN ADMON.USUARIO.APELLIDO_PATERNO IS 'Apellido paterno';
 
   COMMENT ON COLUMN ADMON.USUARIO.APELLIDO_MATERNO IS 'Apellido materno';
 
   COMMENT ON COLUMN ADMON.USUARIO.EMAIL IS 'Correo electrónico';

   COMMENT ON COLUMN ADMON.USUARIO.EMAIL_ALTERNO IS 'Correo electrónico Alterno';
 
   COMMENT ON COLUMN ADMON.USUARIO.ESTATUS_ID IS 'identificador del estatus de registro activo (1=SI y 0=NO)';
 
   COMMENT ON COLUMN ADMON.USUARIO.ELIMINADO_ID IS 'identificador de eliminado (1=SI y 0=NO)';
 
   COMMENT ON COLUMN ADMON.USUARIO.CREACION_FECHA IS 'Fecha de creacion del registro';
 
   COMMENT ON COLUMN ADMON.USUARIO.CREACION_USUARIO IS 'identificador del usuario quien creo el registro';
 
   COMMENT ON COLUMN ADMON.USUARIO.MODIFICACION_FECHA IS 'fecha en la que se modificó el registro';
 
   COMMENT ON COLUMN ADMON.USUARIO.MODIFICACION_USUARIO IS 'identificador del usuario quien modificó el registro';
 
   --COMMENT ON COLUMN ADMON.USUARIO.PERFIL_ID IS 'Perfil al que pertenece el usuario';
 
   COMMENT ON TABLE ADMON.USUARIO  IS 'Tabla de usuarios';


ALTER TABLE ORGANIZACION_USUARIO ADD CORREO_ALTERNO VARCHAR2(50 CHAR);
ALTER TABLE ORGANIZACION_USUARIO ADD DESCRIPCION VARCHAR2(999 CHAR);
ALTER TABLE ORGANIZACION_USUARIO ADD ZONA_ID NUMBER(*,0);
ALTER TABLE ORGANIZACION_USUARIO ADD USUARIO_ID NUMBER(*,0);

ALTER TABLE organizacion_usuario MODIFY USUARIO_ADMON VARCHAR2(100 CHAR);
ALTER TABLE organizacion_usuario MODIFY NOMBRE VARCHAR2(200 CHAR);
ALTER TABLE organizacion_usuario MODIFY APELLIDO_PATERNO VARCHAR2(200 CHAR);
ALTER TABLE organizacion_usuario MODIFY APELLIDO_MATERNO VARCHAR2(200 CHAR);

ALTER TABLE Configuracion_parametro MODIFY VALOR VARCHAR2(999 CHAR);

ALTER TABLE ADMON.USUARIO_ORGANIZACION RENAME TO USUARIO_ORGANIZACION_BK;
    CREATE TABLE ADMON.USUARIO_ORGANIZACION 
   ("USUARIO_ID" NUMBER NOT NULL , 
	"ORGANIZACION_ID" NUMBER NOT NULL , 
	"CREACION_FECHA" DATE DEFAULT SYSDATE NOT NULL, 
	"CREACION_USUARIO" NUMBER(*,0) NOT NULL, 
	"MODIFICACION_FECHA" DATE, 
	"MODIFICACION_USUARIO" NUMBER(*,0), 
	"ESTATUS_ID" NUMBER(*,0) NOT NULL, 
	"ELIMINADO_ID" NUMBER(*,0) DEFAULT 0,  
	 CONSTRAINT "USUARIO_ORGANIZACION_FK1" FOREIGN KEY ("USUARIO_ID")
	  REFERENCES "TAASGO_ADMON"."USUARIO" ("USUARIO_ID") ENABLE, 
	 CONSTRAINT "USUARIO_ORGANIZACION_FK2" FOREIGN KEY ("ORGANIZACION_ID")
	  REFERENCES "TAASGO_ADMON"."ORGANIZACION" ("ORGANIZACION_ID") ENABLE
   ) 




ALTER TABLE ADMON.SEGURIDAD_APLICACION RENAME TO SEGURIDAD_APLICACION_BK;
CREATE TABLE ADMON.SEGURIDAD_APLICACION (
	APLICACION_ID NUMBER(*,0) NOT NULL,
	NOMBRE VARCHAR2(50 BYTE),
	DESCRIPCION VARCHAR2(100 BYTE),
	ETIQUETA_ID NUMBER(10),
	CREACION_FECHA DATE DEFAULT SYSDATE NOT NULL,
	CREACION_USUARIO NUMBER(*,0) NOT NULL,
	MODIFICACION_FECHA DATE,
	MODIFICACION_USUARIO NUMBER(*,0),
	ESTATUS_ID NUMBER(*,0),
	ELIMINADO_ID NUMBER(*,0) DEFAULT 0 ,
	PRIMARY KEY (APLICACION_ID)
);

CREATE TABLE ADMON.SEGURIDAD_APLICACION_PARAMETRO (
    APLICACION_PARAMETRO_ID NUMBER(*,0) NOT NULL,
    APLICACION_ID NUMBER(*,0) NOT NULL,
    LENGUAJE_ID NUMBER(10),
    NOMBRE VARCHAR2(200 CHAR),
    CREACION_FECHA DATE DEFAULT SYSDATE NOT NULL,
    CREACION_USUARIO NUMBER(*,0) NOT NULL,
    MODIFICACION_FECHA DATE,
    MODIFICACION_USUARIO NUMBER(*,0),
    PRIMARY KEY ("APLICACION_PARAMETRO_ID"),
    CONSTRAINT FK_SEGURIDAD_APLICACION_PAR FOREIGN KEY("APLICACION_ID") REFERENCES SEGURIDAD_APLICACION("APLICACION_ID")
);

ALTER TABLE ADMON.SEGURIDAD_MODULO RENAME TO SEGURIDAD_MODULO_BK;
CREATE TABLE ADMON.SEGURIDAD_MODULO (
	MODULO_ID NUMBER(*,0)  NOT NULL,
	APLICACION_ID NUMBER(*,0)  NOT NULL,
	URL VARCHAR2(300 CHAR),
	ORDEN NUMBER(10),
	NOMBRE_ACCION VARCHAR2(100 CHAR),
	NOMBRE_OBJETO VARCHAR2(20 CHAR),
	DESCRIPCION VARCHAR2(60 CHAR),
	HTML_ID VARCHAR2(100 CHAR),
	CREACION_FECHA DATE DEFAULT SYSDATE NOT NULL,
	CREACION_USUARIO NUMBER(10) NOT NULL,
	MODIFICACION_FECHA DATE,
	MODIFICACION_USUARIO NUMBER(10),
	ESTATUS_ID NUMBER(*,0) DEFAULT 1  NOT NULL,
	ELIMINADO_ID NUMBER(*,0) DEFAULT 0 NOT NULL,
	ICONO VARCHAR2(50 BYTE),
	COLOR_TITULO VARCHAR2(50 BYTE),
	COLOR_INFO VARCHAR2(50 BYTE),
	COLOR_MENU VARCHAR2(50 BYTE),
	PRIMARY KEY (MODULO_ID)
);

ALTER TABLE ADMON.SEGURIDAD_MODULO_PARAMETROS RENAME TO SEGURIDAD_MODULO_PARAMETROS;
CREATE TABLE ADMON.SEGURIDAD_MODULO_PARAMETROS (
	MODULO_PARAMETRO_ID NUMBER(*,0) NOT NULL,
	MODULO_ID NUMBER(*,0),
	LENGUAJE_ID NUMBER(*,0),
	NOMBRE VARCHAR2(200 CHAR),
	CREACION_FECHA DATE DEFAULT SYSDATE NOT NULL,
	CREACION_USUARIO NUMBER(*,0) NOT NULL,
	MODIFICACION_FECHA DATE,
	MODIFICACION_USUARIO NUMBER(*,0),
	PRIMARY KEY (MODULO_PARAMETRO_ID),
	CONSTRAINT FK_SEGURIDAD_MODULO_PAR FOREIGN KEY("MODULO_ID") REFERENCES SEGURIDAD_MODULO("MODULO_ID")
);

ALTER TABLE ADMON.SEGURIDAD_OPERACION RENAME TO SEGURIDAD_OPERACION_BK;
CREATE TABLE ADMON.SEGURIDAD_OPERACION (
	OPERACION_ID NUMBER(*,0) NOT NULL,
	MODULO_ID NUMBER(*,0) NOT NULL,
	APLICACION_ID NUMBER(*,0) NOT NULL,
	URL VARCHAR2(300 CHAR),
	ORDEN NUMBER(*,0),
	DESCRIPCION VARCHAR2(60 CHAR),
	NOMBRE_ACCION VARCHAR2(100 CHAR),
	HTML_ID VARCHAR2(100 CHAR),
	CREACION_FECHA DATE DEFAULT SYSDATE NOT NULL,
	CREACION_USUARIO NUMBER(*,0) NOT NULL,
	MODIFICACION_FECHA DATE,
	MODIFICACION_USUARIO NUMBER(*,0),
	ESTATUS_ID NUMBER(*,0) DEFAULT 1  NOT NULL,
	ELIMINADO_ID NUMBER(*,0) DEFAULT 0  NOT NULL,
	PRIMARY KEY (OPERACION_ID)
);

ALTER TABLE ADMON.SEGURIDAD_OPERACION_PARAMETROS RENAME TO SEGURIDAD_OPERACION_PARAM_BK;
CREATE TABLE ADMON.SEGURIDAD_OPERACION_PARAMETROS(
	OPERACION_PARAMETRO_ID NUMBER(*,0) NOT NULL,
	OPERACION_ID NUMBER(*,0),
	LENGUAJE_ID NUMBER(*,0),
	NOMBRE VARCHAR2(200 CHAR),
	CREACION_FECHA DATE DEFAULT SYSDATE NOT NULL,
	CREACION_USUARIO NUMBER(*,0) NOT NULL,
	MODIFICACION_FECHA DATE,
	MODIFICACION_USUARIO NUMBER(*,0),
	PRIMARY KEY (OPERACION_PARAMETRO_ID)
	CONSTRAINT FK_SEGURIDAD_OPERACION_PAR FOREIGN KEY("OPERACION_ID") REFERENCES SEGURIDAD_OPERACION("OPERACION_ID")
);

ALTER TABLE ADMON.SEGURIDAD_OPERA_FUNCIONALIDAD RENAME TO SEGURIDAD_OPERA_FUNC_BK;
CREATE TABLE ADMON.SEGURIDAD_OPERA_FUNCIONALIDAD
(
   FUNCIONALIDAD_ID        NUMBER(*,0) NOT NULL,
   OPERACION_ID            NUMBER(*,0) NOT NULL,
   APLICACION_ID           NUMBER(*,0) NOT NULL,
   MODULO_ID               NUMBER(*,0) NOT NULL,
   HTML_ID                 VARCHAR2 (30 CHAR),
   TIPO_FUNCIONALIDAD_ID   NUMBER(*,0),
   DESCRIPCION             VARCHAR2 (60 CHAR),
   METODO                  VARCHAR2 (200),
   CREACION_FECHA          DATE DEFAULT SYSDATE NOT NULL,
   CREACION_USUARIO        NUMBER (10) NOT NULL,
   MODIFICACION_FECHA      DATE,
   MODIFICACION_USUARIO    NUMBER(*,0),
   ESTATUS_ID              NUMBER(*,0) NOT NULL,
   ELIMINADO_ID            NUMBER(*,0) DEFAULT 0 NOT NULL,
   PRIMARY KEY (FUNCIONALIDAD_ID)
);

ALTER TABLE ADMON.SEGURIDAD_OPER_FUNC_PARAMETROS RENAME TO SEGURIDAD_OPERA_FUNC_PARAM_BK;
CREATE TABLE ADMON.SEGURIDAD_OPER_FUNC_PARAMETROS (
	OPER_FUNC_PARAMETRO_ID NUMBER(*,0) NOT NULL,
	FUNCIONALIDAD_ID NUMBER(*,0), 
	LENGUAJE_ID NUMBER(*,0) ,
	NOMBRE VARCHAR2(200 CHAR),
	CREACION_FECHA DATE DEFAULT SYSDATE NOT NULL,
	CREACION_USUARIO NUMBER(*,0)  NOT NULL,
	MODIFICACION_FECHA DATE,
	MODIFICACION_USUARIO NUMBER(*,0) ,
	PRIMARY KEY (OPER_FUNC_PARAMETRO_ID)
	CONSTRAINT FK_SEGURIDAD_FUNC_PAR FOREIGN KEY("FUNCIONALIDAD_ID") REFERENCES SEGURIDAD_OPERA_FUNCIONALIDAD("FUNCIONALIDAD_ID")
);

ALTER TABLE ADMON.SEGURIDAD_ROL RENAME TO SEGURIDAD_ROL_BK;
CREATE TABLE ADMON.SEGURIDAD_ROL(
    ROL_ID NUMBER(*,0)  NOT NULL,
    APLICACION_ID NUMBER(*,0)  NOT NULL,
    NOMBRE VARCHAR2(200 CHAR),
    NOMBRE_INGLES VARCHAR(200 CHAR),
    DESCRIPCION VARCHAR(999 CHAR),
    CREACION_FECHA DATE DEFAULT SYSDATE NOT NULL,
  	CREACION_USUARIO NUMBER(10) NOT NULL,
  	MODIFICACION_FECHA DATE,
  	MODIFICACION_USUARIO NUMBER(*,0) ,
  	ESTATUS_ID NUMBER(*,0),
  	ELIMINADO_ID NUMBER(*,0)  DEFAULT 0 NOT NULL,
    PRIMARY KEY (ROL_ID)
);

CREATE TABLE ADMON.SEGURIDAD_ROL_PARAMETROS(
    ROL_PARAMETRO_ID NUMBER(*,0) NOT NULL,
	ROL_ID NUMBER(*,0),
	LENGUAJE_ID NUMBER(*,0),
	NOMBRE VARCHAR2(200 CHAR),
	CREACION_FECHA DATE DEFAULT SYSDATE NOT NULL,
	CREACION_USUARIO NUMBER(*,0) NOT NULL,
	MODIFICACION_FECHA DATE,
	MODIFICACION_USUARIO NUMBER(*,0),
	PRIMARY KEY (ROL_PARAMETRO_ID),
	CONSTRAINT FK_ROL_OPERACION_PAR FOREIGN KEY("ROL_ID") REFERENCES SEGURIDAD_ROL("ROL_ID")
);

ALTER TABLE ADMON.SEGURIDAD_PERFIL RENAME TO SEGURIDAD_PERFIL_BK;
CREATE TABLE ADMON.SEGURIDAD_PERFIL(
    PERFIL_ID NUMBER(*,0)  NOT NULL,
    APLICACION_ID NUMBER(*,0)  NOT NULL,
    NOMBRE VARCHAR2(200 CHAR),
    DESCRIPCION VARCHAR(999 CHAR),
    CREACION_FECHA DATE DEFAULT SYSDATE NOT NULL,
  	CREACION_USUARIO NUMBER(*,0) NOT NULL,
  	MODIFICACION_FECHA DATE,
  	MODIFICACION_USUARIO NUMBER(*,0) ,
  	ESTATUS_ID NUMBER(*,0)  NOT NULL,
  	ELIMINADO_ID NUMBER(*,0)  DEFAULT 0 NOT NULL,
    PRIMARY KEY(PERFIL_ID)
);

CREATE TABLE ADMON.SEGURIDAD_PERFIL_PARAMETROS(
    PERFIL_PARAMETRO_ID NUMBER(*,0) NOT NULL,
	PERFIL_ID NUMBER(*,0),
	LENGUAJE_ID NUMBER(*,0),
	NOMBRE VARCHAR2(200 CHAR),
	CREACION_FECHA DATE DEFAULT SYSDATE NOT NULL,
	CREACION_USUARIO NUMBER(*,0) NOT NULL,
	MODIFICACION_FECHA DATE,
	MODIFICACION_USUARIO NUMBER(*,0),
	PRIMARY KEY (PERFIL_PARAMETRO_ID),
	CONSTRAINT FK_SEGURIDAD_PERFIL_PAR FOREIGN KEY("PERFIL_ID") REFERENCES SEGURIDAD_PERFIL("PERFIL_ID")
);

ALTER TABLE ADMON.SEGURIDAD_PERFIL_ROL RENAME TO SEGURIDAD_PERFIL_ROL_BK;
CREATE TABLE ADMON.SEGURIDAD_PERFIL_ROL(
    PERFIL_ROL_ID NUMBER(*,0) NOT NULL,
    PERFIL_ID NUMBER(*,0) NOT NULL,
    ROL_ID NUMBER(*,0) NOT NULL,
    APLICACION_ID NUMBER(*,0) NOT NULL,
    CREACION_FECHA DATE DEFAULT SYSDATE NOT NULL,
  	CREACION_USUARIO NUMBER(*,0) NOT NULL,
  	MODIFICACION_FECHA DATE,
  	MODIFICACION_USUARIO NUMBER(*,0),
    PRIMARY KEY("PERFIL_ROL_ID"),
    CONSTRAINT FK_SEGURIDAD_PERFIL_ROL_PERFIL FOREIGN KEY("PERFIL_ID") REFERENCES SEGURIDAD_PERFIL("PERFIL_ID"),
    CONSTRAINT FK_SEGURIDAD_PERFIL_ROL_ROLES FOREIGN KEY("ROL_ID") REFERENCES SEGURIDAD_ROL("ROL_ID")
);

ALTER TABLE ADMON.SEGURIDAD_FUNCION_RESTRICCION RENAME TO SEGURIDAD_FUNC_RESTRICCION_BK;
CREATE TABLE ADMON.SEGURIDAD_FUNCION_RESTRICCION(
    APLICACION_ID NUMBER(*,0) NOT NULL,
    FUNCIONALIDAD_ID NUMBER(*,0) NOT NULL,
    ROL_ID NUMBER(*,0) NOT NULL,
    ACTIVO NUMBER(*,0) NOT NULL,
    PRIMARY KEY("FUNCIONALIDAD_ID", "ROL_ID"),
    CONSTRAINT FK_RESTRICCION_ROL_FUNC_FUN FOREIGN KEY("FUNCIONALIDAD_ID") REFERENCES SEGURIDAD_OPERA_FUNCIONALIDAD("FUNCIONALIDAD_ID"),
    CONSTRAINT FK_RESTRICCION_ROL_FUNC_ROL FOREIGN KEY("ROL_ID") REFERENCES SEGURIDAD_ROL(ROL_ID)
);

ALTER TABLE ADMON.SEGURIDAD_ROL_OPERACION RENAME TO SEGURIDAD_ROL_OPERACION_BK;
CREATE TABLE ADMON.SEGURIDAD_ROL_OPERACION(
    ROL_OPERACION_ID NUMBER(*,0) NOT NULL,
    ROL_ID NUMBER(*,0) NOT NULL,
    OPERACION_ID NUMBER(*,0),
    APLICACION_ID NUMBER(*,0) NOT NULL,
    CREACION_FECHA DATE DEFAULT SYSDATE NOT NULL,
	CREACION_USUARIO NUMBER(*,0) NOT NULL,
    MODIFICACION_FECHA DATE,
	MODIFICACION_USUARIO NUMBER(*,0),
    PRIMARY KEY("ROL_OPERACION_ID"),
    CONSTRAINT FK_SEGURIDAD_ROL_OPERACION_OPR FOREIGN KEY("OPERACION_ID") REFERENCES SEGURIDAD_OPERACION("OPERACION_ID"),
    CONSTRAINT FK_SEGURIDAD_ROL_OPERACION_ROL FOREIGN KEY("ROL_ID") REFERENCES SEGURIDAD_ROL("ROL_ID")
);

ALTER TABLE ADMON.SEGURIDAD_ROL_RESTRICCION_PAR RENAME TO SEGURIDAD_ROL_RESTRIC_PAR_BK;
CREATE TABLE ADMON.SEGURIDAD_ROL_RESTRICCION_PAR(
    ROL_ID NUMBER(*,0) NOT NULL,
    CATALOGO_PARAMETRO_ID NUMBER(*,0) NOT NULL,
    APLICACION_ID NUMBER(*,0) NOT NULL,
    CREACION_FECHA DATE DEFAULT SYSDATE NOT NULL,
    CREACION_USUARIO NUMBER(*,0) NOT NULL,
    ORGANIZACION_ID NUMBER(*,0) NOT NULL,
    PRIMARY KEY("ROL_ID","CATALOGO_PARAMETRO_ID"),
    CONSTRAINT FK_RESTRICCION_ROL_FUNCION_ROL FOREIGN KEY("ROL_ID") REFERENCES SEGURIDAD_ROL("ROL_ID")
);  


ALTER TABLE ADMON.SEGURIDAD_USUARIO_PERFIL RENAME TO SEGURIDAD_USUARIO_PERFIL_BK;
  CREATE TABLE ADMON.SEGURIDAD_USUARIO_PERFIL
   (
   	"USUARIO_ID" NUMBER(*,0)  NOT NULL , 
	"APLICACION_ID" NUMBER(*,0) NOT NULL , 
	"PERFIL_ID" NUMBER(*,0) NOT NULL , 
	"CREACION_FECHA" DATE DEFAULT SYSDATE  NOT NULL , 
	"CREACION_USUARIO" NUMBER(*,0)  NOT NULL , 
	"MODIFICACION_FECHA" DATE, 
	"MODIFICACION_USUARIO" NUMBER(*,0), 
	"ORGANIZACION_ID" NUMBER NOT NULL , 
	 CONSTRAINT "PK_SEG_USUARIO_PERFIL" PRIMARY KEY ("USUARIO_ID", "PERFIL_ID", "ORGANIZACION_ID")
	 CONSTRAINT "FK_SEGU_USUARIO_PERFIL_ORG" FOREIGN KEY ("ORGANIZACION_ID")
	  REFERENCES "TAASGO_ADMON"."ORGANIZACION" ("ORGANIZACION_ID") ENABLE, 
	 CONSTRAINT "FK_SEG_USUARIO_PERFIL_PERFIL" FOREIGN KEY ("PERFIL_ID", "ORGANIZACION_ID")
	  REFERENCES "TAASGO_ADMON"."SEGURIDAD_PERFIL" ("PERFIL_ID", "ORGANIZACION_ID") ENABLE, 
	 CONSTRAINT "FK_SEG_USUARIO_PERFIL_USUARIO" FOREIGN KEY ("USUARIO_ID")
	  REFERENCES "TAASGO_ADMON"."USUARIO" ("USUARIO_ID") ENABLE
   );

  

 