
	 UPDATE CONFIGURACION_PARAMETRO
	 SET  VALOR = '/app/taasgo/repositorio/web/'
	 WHERE TAASGO.CONFIGURACION_PARAMETRO_ID = 81;
	 
	 UPDATE CONFIGURACION_PARAMETRO
	 SET  VALOR = '/app/taasgo/repositorio/taquilla/organizacion/'
	 WHERE TAASGO.CONFIGURACION_PARAMETRO_ID = 82;
	 
	  UPDATE CONFIGURACION_PARAMETRO
	 SET  VALOR = '/app/taasgo/repositorio/impresiones/organizacion/'
	 WHERE TAASGO.CONFIGURACION_PARAMETRO_ID = 83;